---
name: CI

env:
  # https://github.com/actions/virtual-environments/issues/1499
  MAVEN_CLI_OPTS: '-ntp --batch-mode --errors --fail-at-end --show-version -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dstyle.color=always'
  TESTCONTAINERS_RYUK_DISABLED: 'true'

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.env.KEYCLOAK_VERSION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-${{ matrix.env.KEYCLOAK_VERSION }}

      - name: Build & Test
        run: ./mvnw ${MAVEN_CLI_OPTS} clean verify

      - name: Create Checksum
        run: |
          cp target/keycloak-environment-resource-version.jar keycloak-environment-resource-version.jar
          sha512sum keycloak-environment-resource-version.jar > keycloak-environment-resource-version.jar.sha512

      - uses: actions/upload-artifact@v3
        with:
          name: keycloak-environment-resource-version
          if-no-files-found: error
          path: |
            keycloak-environment-resource-version.jar
            keycloak-environment-resource-version.jar.sha512

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'rc') }}
          files: |
            assets/keycloak-environment-resource-version/keycloak-environment-resource-version.jar
            assets/keycloak-environment-resource-version/keycloak-environment-resource-version.jar.sha256
